version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: "npm"
      directory: "/src-ui"
      schedule:
          interval: "daily"
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-major"]
      labels:
          - "dependencies-ui"
      open-pull-requests-limit: 10
      # Gruppiere alle npm-Updates in einem Pull Request
      groups:
          npm-dependencies:
              patterns:
                  - "**"

    # Enable version updates for gradle
    - package-ecosystem: "gradle"
      directory: "/src"
      schedule:
          interval: "daily"
      labels:
          - "dependencies-backend"
      open-pull-requests-limit: 10
      # Gruppiere alle Gradle-Updates in einem Pull Request
      groups:
          gradle-dependencies:
              patterns:
                  - "**"

    # Enable version updates for docker
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "dependencies-docker"
      open-pull-requests-limit: 10
      # Gruppiere alle Docker-Updates in einem Pull Request
      groups:
          docker-dependencies:
              patterns:
                  - "**"

    # Enable version updates for github-actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "dependencies-github-actions"
      open-pull-requests-limit: 10
      # Gruppiere alle GitHub Actions-Updates in einem Pull Request
      groups:
          github-actions-dependencies:
              patterns:
                  - "**"
