version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    image: 12ukas/symptothermapp-backend:latest
    ports:
      - "8088:8080"
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3232}
      # - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      # - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      # - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - db-data:/app/db
    networks:
      - shared-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    container_name: frontend
    image: 12ukas/symptothermapp-frontend:latest
    ports:
      - "3232:80"
    environment:
      - NODE_ENV=development
    networks:
      - shared-network

volumes:
  db-data:

networks:
  shared-network:
    driver: bridge
