services:
    db:
        image: docker.io/library/postgres:16
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: symptothermapp
            POSTGRES_USER: symptothermapp
            POSTGRES_PASSWORD: symptothermapp

    backend:
        image: 12ukas/symptothermapp-backend:latest
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "8088:8080"
        volumes:
            - data:/usr/src/symptothermapp/data
        build:
            context: ./src
            # dockerfile: Dockerfile
        environment:
            POSTGRES_HOST: symptothermapp
            POSTGRES_PORT: 5432
            POSTGRES_NAME: symptothermapp
            POSTGRES_USER: symptothermapp
            POSTGRES_PASSWORD: symptothermapp
        # networks:
        #     - shared-network

    frontend:
        image: 12ukas/symptothermapp-frontend:latest
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "3232:80"
        build:
            context: ./src-ui
            # dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        environment:
            - NODE_ENV=development
        # networks:
        #     - shared-network

    postgres:
        image: postgres:16.4-alpine
        environment:
            POSTGRES_DB: symptothermapp
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        # networks:
        #     - shared-network

volumes:
    data:
# networks:
#     shared-network:
#         driver: bridge
