spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:default}
---
spring:
    config:
        activate:
            on-profile: default
    application:
        name: symptothermapp
    datasource:
        url: ${DB_PATH:jdbc:postgresql://localhost:5432/symptothermapp}
        username: ${DB_USER:symptothermapp}
        password: ${DB_PASSWORD:symptothermapp}
    jpa:
        open-in-view: false
        properties:
            hibernate:
                ddl-auto: validate
    sql:
        init:
            mode: always
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
app:
    version: "@project.version@"
springdoc:
    swagger-ui:
        path: /swagger-ui.html

---
spring:
    config:
        activate:
            on-profile: openapi
    application:
        name: symptothermapp
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.H2Dialect
    liquibase:
        enabled: false
app:
    version: "@project.version@"
springdoc:
    swagger-ui:
        path: /swagger-ui.html
