spring:
    sql:
        init:
            # The default value is 'embedded', which only works for in-memory databases.
            # Since we're using a 'non-embedded' database here, we now need to set this to 'always'.
            mode: always
app:
    version: "@project.version@"
    frontend:
        port: 3232
