spring:
    application:
        name: symptothermapp
    datasource:
        url: ${DB_PATH:jdbc:postgresql://localhost:5432/symptothermapp}
        username: ${DB_USER:symptothermapp}
        password: ${DB_PASSWORD:symptothermapp}
    jpa:
        open-in-view: false
        properties:
            hibernate:
                ddl-auto: validate
    sql:
        init:
            mode: always
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
app:
    version: "@project.version@"
springdoc:
    swagger-ui:
        path: /swagger-ui.html
